# Generated by Django 5.0.3 on 2024-04-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chapter_name", models.CharField(max_length=255)),
                ("notes", models.FileField(upload_to="notes/")),
                ("video_url", models.URLField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
